ReferenceError: fetch is not defined
    at Object.execute (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\commands\cat.js:7:26)
    at Client.<anonymous> (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\main.js:80:11)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: getaddrinfo ENOTFOUND discord.com
    at RequestHandler.execute (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\Client.js:223:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: getaddrinfo ENOTFOUND discord.com
    at RequestHandler.execute (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\Client.js:223:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: getaddrinfo ENOTFOUND discord.com
    at RequestHandler.execute (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\Client.js:223:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received Promise { <pending> }
    at setInterval (timers.js:187:3)
    at Client.<anonymous> (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\main.js:24:2)
    at Client.emit (events.js:327:22)
    at WebSocketManager.triggerClientReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10) {
  code: 'ERR_INVALID_CALLBACK'
}
HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: getaddrinfo ENOTFOUND discord.com
    at RequestHandler.execute (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\Client.js:223:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'
}
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received Promise { <pending> }
    at setInterval (timers.js:187:3)
    at Client.<anonymous> (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\main.js:24:2)
    at Client.emit (events.js:327:22)
    at WebSocketManager.triggerClientReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (C:\Users\27747\OneDrive - Sint-Paulusschool\DiscordBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10) {
  code: 'ERR_INVALID_CALLBACK'
}
